### ISSUE TITLE
Pleaase remove some FUD from the README

### ISSUE THREAD

**Issue by WebReflection** [corpusculejs/custom-builtin-elements#13]
It actually sadden me you decided to write yet another polyfill, but you should remove this inaccurate, and unfair, line from your README:

> Unfortunately, it has some problems that make it hard to use

No, [@ungap/custom-elements-builtin](https://github.com/ungap/custom-elements-builtin) has **zero issues** and there is an [easy workaround](https://github.com/ungap/custom-elements-new#readme) for the constructor, which is the only caveat, and [well documented](https://github.com/ungap/custom-elements-builtin#constructor-caveat) in the README.

Writing FUD about competitors is not really a great way to present a new polyfill, and I also wish next time you file an issue or propose a solution, instead of doing this.

Best Regards.

**Comment by WebReflection** [comment]
## Suggestion

Differently from [@ungap/custom-elements-builtin](https://github.com/ungap/custom-elements-builtin), this polyfills allow the usage of the constructor, which is apparently a [caveat](https://github.com/ungap/custom-elements-builtin#constructor-caveat) in this alternative library.
- - -

Above sentence is respectful, it doesn't mention the library _has some problems that make it hard to use_, specially because all my production libraries are based on it, and none of those ever cared about the construction limitation so, thanks for considering this change.

**Comment by WebReflection** [comment]
Pull Request created, this is how Open Source _should_ work.

**Comment by Lodin** [comment]
I'm sorry that the words I chose was rude and inappropriate. That was completely unintentional. Moreover, I appreciate your work and everything you've made for the web. This polyfill was just a crazy idea at the first, so I didn't even think about filing the issue or suggesting this idea as a solution. And after it was created, I just published it and described the reason I developed it. Sorry for choosing the words so entirely wrong and thank you for rephrasing it in the respectful way.

**Comment by WebReflection** [comment]
@Lodin thanks for coming back with background and reasons. The thing is, I have done that dance of patching all native classes [more than 4 years ago](https://github.com/WebReflection/html-class/blob/master/index.js#L45) and my conclusion is that it's both obtrusive (as it touches all native classes, but then again, which polyfill isn't obtrusive?) and heavy, plus it was working badly with older transpilers.

Maybe the situation changed these days, so I'll watch this project to see how it goes, because if it goes well, I might as well patch all native classes too and solve the `constructor` caveat in there too.

This is why competition is always welcome, as long as it's fair.

Have a nice weekend 👋

**Comment by WebReflection** [comment]
P.S. 

> this polyfills allow

should be

> this polyfill allows

apologies for the typo in the MR
